languageCode = "en-us"
title = "Massively"
baseURL = "https://davetroeger.github.io/jetlag-web/"
theme = "../.."

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

[params.settings]
    googleanalytics = ""

