languageCode = "en-us"
title = "Massively"
baseURL = "http://localhost:1313/"
theme = "../.."

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

[params.settings]
    googleanalytics = ""

