languageCode = "en-us"
title = "Test"
baseURL = ""
theme = "../.."

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

[params.settings]
    googleanalytics = ""
    disqus = ""

